<?php
/*---------------------------------------------------------------
author:	alim karim
date:	Feb 02, 2007
file:	tng_display_form.php

desc:	webpage to render a form that the user can fill out
---------------------------------------------------------------*/
header('Pragma: no-cache'); 
header("Cache-Control: no-cache, must-revalidate"); // HTTP/1.1
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT"); // Date in the past

include('tng_display_form_code.php');
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link href="style.css" rel="stylesheet" type="text/css" />
<title>Fill Form</title>
<script language="javascript">
var file_count = 0;
var file_prefix = 'file_';

///
/// add_file_input
/// create a set of elements on the form that allow
/// a file to be uploaded with the submission of 
/// a form.
///
function add_file_input(){	 
	var file_div = document.getElementById('form_files');
	file_count++;
	var file_desc_label = document.createElement('label');
	file_desc_label.setAttribute('for', 'txt_area_file_description');
	file_desc_label.setAttribute('class', 'lbl_regular');
	file_desc_label.innerHTML = "File Description";
	file_div.appendChild(file_desc_label);
	
	var end_tag = document.createElement('br');
	file_div.appendChild(end_tag);
	
	var file_desc = document.createElement('textarea');
	file_desc.setAttribute('class', 'txt_area_file_description');
	file_div.appendChild(file_desc);
	
	var file_input = document.createElement('input');
	file_input.setAttribute('type', 'file');
	file_input.setAttribute('id', file_prefix + file_count);
	file_input.setAttribute('name', file_prefix + file_count);
	file_input.setAttribute('class', 'input_file'); 
	file_div.appendChild(file_input);
	
	var end_tag = document.createElement('br');
	file_div.appendChild(end_tag);
	
	var end_tag = document.createElement('hr');
	file_div.appendChild(end_tag);
	
	var end_tag = document.createElement('br');
	file_div.appendChild(end_tag);	
}

///
/// submit_form()
/// submit the form if file validation
/// succeeds
///
function submit_form(){
	if(validate_files() == false)
		alert('You are missing a .shp, .dbf or a .shx file');
	else{ // check passed, submit the form
		elt = document.getElementById('form_submitted');
		elt.value = "submitted";
		document.forms[0].submit();
	}
}

///
/// validate_files()
/// check to see if every shapefile
/// has a corresponding dbf and shx files.
/// note that the user can get away with providing
/// unrelated shape, dbf and index files - names are
/// not checked. for instance, the user could 
/// upload abc.shp, abc.dbf and xyz.shx.
///
function validate_files(){
	var shp_count = 0;
	var dbf_count = 0;
	var shx_count = 0;
	
	for(var i = 0; i < file_count; i++){
		var file_num = i + 1;
		var elt_id = file_prefix + file_num;
		var file_input = document.getElementById(elt_id);
		// this is needed in case the user clicks 'Add file'
		// and then leaves the contents of the file input
		// blank
		if(file_input.value.length > 0){
			var file_name = file_input.value.substring(file_input.value.lastIndexOf("/") + 1, file_input.value.length);
			var file_ext = file_name.substring(file_name.lastIndexOf(".") + 1, file_name.length);
			if(file_ext == "shp")
				shp_count++;
			else if(file_ext == "dbf")
				dbf_count++;
			else if(file_ext == "shx")
				shx_count++;
			else{
				// non-spatial file, do not increment counters
			}
		}
	}
	
	if((shp_count == dbf_count) && (shp_count == shx_count))
		return true;
	else
		return false;
}

</script>
</head>
<body>
<div id="leftcol">wefwef </div>
	<form id="tng_display_form" 
		name="tng_display_form" 
		method="post" 
		enctype="multipart/form-data" 
		action="tng_display_form.php">
		<div id="content">
			<h3> Parent Submission ID: 
				<input type="text" id="parent_submission" name="parent_submission" size="30"/>
			</h3>
			<p> Please leave this field blank if you do not
				wish to link this submission with a previously
				made submission.
		</div>
		<div id="content">	
			<br/>
	      		<?php
				// print out the html generated by the stylesheet
				// from the xml
				echo $generated_form_html;
				?>
			<hr />
			<input type="hidden" id="form_submitted" name="form_submitted" value=""/>
			<!-- 
				the buttons below are disabled 
				if the form is being displayed in
				read only mode.
			-->
			<input type="button" 
					onclick="add_file_input()" 
					value="Add File" 
					class="button" 
					<?php if($_SESSION['readonly'] == 'true') echo "disabled"; ?>
					/>
			<input type="button" 
					onclick="submit_form()" 
					value="Submit" 
					class="button" 
					<?php if($_SESSION['readonly'] == 'true') echo "disabled"; ?> 
					/>
			<hr />
			<div id="form_files">
				<!-- this is where file input elements will be added -->
			</div>
		</div>
	</form>

<div id="rightcol"> wefwef  </div> 

</body>
</html>
